CREATE DATABASE FACULDADE;
USE FACULDADE;

CREATE TABLE ALUNOS(
COD_CURSO INT     PRIMARY KEY AUTO_INCREMENT ,
NOME VARCHAR (60),
COD_ALUNO INT (25)
);


CREATE TABLE CURSOS (
COD_CURSO INT PRIMARY KEY ,
NOME_CURSO VARCHAR(30),
FOREIGN KEY (COD_CURSO) REFERENCES ALUNOS( COD_CURSO) 
);

INSERT INTO ALUNOS (COD_CURSO,NOME,COD_ALUNO) VALUES (2,'ELAINE MARTINS',3);
INSERT INTO CURSOS (COD_CURSO, NOME_CURSO)VALUES (2,'DADOS');












